### ISSUE TITLE
Suggestions about recurrence

### ISSUE THREAD

**Issue by AiwassPrime** [AY2021S2-CS2103T-T13-2/tp#136]
Scenario: A student wants to use the ModuleBook like NUSmod. He will only add tasks once a semester and make them automatically recur. He will not enter any command throughout the whole semester.
Problem: The ModuleBook will stop updating after one week. No command means no save to storage, the ModuleBook will keep updating the original date by one week, when you open the module book. Also mentioned in #108 
Suggested solution: As simple as "while (!isUpToDate) recur()" when open the module book + store after updating

Scenario: A student is taking a lecture with his ModuleBook open. Now the lecture is over, he wants to know when will be the next lecture (and maybe he is really bad at calculation?)
Problem: He has no choice but to close the ModuleBook and reopen it to see the updated time.
Suggested solution: Add a refresh command that refreshes all tasks in the list, if they are recurTasks and not up to date.

The one-shot solution to the previous two problems: Add the refresh command, and execute it automatically when you open the ModuleBook.

Problem: "recur 1 r/daily" is almost identical to "edit 1 r/daily". If we still decide to keep recurCommand, we have to get prepared for criticizes such as "If they are doing a similar job, why you guys only have this particular one for recur only?" during the peer review.
Solution: Delete recurCommand or implement all the rest, I really don't think we should stay anywhere in the middle.
PS: tagCommand is different.

After fixing all of these, we should also implement all kinds of testing about recurrence.

**Comment by umergta** [comment]
hmm i definitely agree with you that we shouldnt stay in the middle.

When implementing the recur command, I thought it was a good to have a command on its own because:
1. Personally, i would have more 'one-time' tasks than recurring tasks if im using a a task manager. E.g. we would only have 1 _assignment 1_ in a module. So for recurring tasks, realistically speaking, it should be made into a command rather than just a normal field like 'workload' for example. This is also a justification we can give for the criticism on 'why does _recur_ have to be a command on it's own' if we get it?

2. With regards to your 1st problem, I am not quite sure as to why the book will stop updating weekly? If a task is recurring weekly, it will refresh the deadline every week regardless, no? Might need some clarification there haha sorry

3. The second scenario is actually a v important consideration. One possible implementation can be when a user marks task as _done_, we can update the deadline (and remove starttime maybe), so that the user can see the next deadline already? what do you think? Another possible solution would be to maybe add a _next deadline:_ field in the task card which is way simpler i think?

For the refresh command, i think it is a bit unsafe to add a new command with only a day left because I think quite a few changes would need to be made? and we only have (only a day at most) to implemement the feature? I am scared that it will be too tight for v1.3 deadline? 

Overall, I am still fine with either though cuz for me, both ways work fine and (i think) either way can be justified hahaha

**Comment by AiwassPrime** [comment]
> hmm i definitely agree with you that we shouldnt stay in the middle.
> 
> When implementing the recur command, I thought it was a good to have a command on its own because:
> 
> 1. Personally, i would have more 'one-time' tasks than recurring tasks if im using a a task manager. E.g. we would only have 1 _assignment 1_ in a module. So for recurring tasks, realistically speaking, it should be made into a command rather than just a normal field like 'workload' for example. This is also a justification we can give for the criticism on 'why does _recur_ have to be a command on it's own' if we get it?
> 2. With regards to your 1st problem, I am not quite sure as to why the book will stop updating weekly? If a task is recurring weekly, it will refresh the deadline every week regardless, no? Might need some clarification there haha sorry
> 3. The second scenario is actually a v important consideration. One possible implementation can be when a user marks task as _done_, we can update the deadline (and remove starttime maybe), so that the user can see the next deadline already? what do you think? Another possible solution would be to maybe add a _next deadline:_ field in the task card which is way simpler i think?
> 
> For the refresh command, i think it is a bit unsafe to add a new command with only a day left because I think quite a few changes would need to be made? and we only have (only a day at most) to implemement the feature? I am scared that it will be too tight for v1.3 deadline?
> 
> Overall, I am still fine with either though cuz for me, both ways work fine and (i think) either way can be justified hahaha

For 1, I think your justification is also valid, maybe need a vote?
For 2, let's say you added a task whose deadline is 2021-4-1, recurs daily, and then you close the software. After two months, you open the software again, it will become 2021-4-2. But if you do not enter any command and close the software straight away, the storage will not be updated, it is still 2021-4-1.

**Comment by umergta** [comment]
@yhtMinceraft1010X @QY-H00 @figo2127 what do u guys think?

**Comment by yhtMinceraft1010X** [comment]
Personally, I think that if 2 commands share the exact same functionality, we might as well keep to one single command.

**Comment by figo2127** [comment]
I feel that its better to keep things simple, but if its too troublesome maybe we can state somewhere in the DG/UG on the 2 very similar commands. For @AiwassPrime and @umergta  2nd problem, I think the ModuleBook should check the deadlines and recurrence on every start-up so that the "updating" does not get stuck  after 2 months of not opening the app.
